package ejb.classes;

import app.entities.Tovar;
import app.model.DAO;
import ejb.interfaces.SimpleBeanRemote;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import javax.activation.DataSource;
import javax.annotation.Resource;
import javax.ejb.LocalBean;
import javax.ejb.SessionContext;
import javax.ejb.Stateless;
import javax.naming.InitialContext;
import java.sql.Connection;
import java.util.List;
@Resource(name="TestDS", type=javax.sql.DataSource.class)
@Stateless
@LocalBean
public class SimpleBean implements SimpleBeanRemote {
    public void setSessionContext(SessionContext sessionContext) {
        DataSource dataSource = (DataSource)
                sessionContext.lookup("clients");
    }
private Connection connection;
    public void someOtherMethod() throws Exception {
        InitialContext initialContext = new InitialContext();
        DataSource dataSource = (DataSource)
                initialContext.lookup("java:comp/env/jdbc/clients");
    }
    @Override
    public List<Tovar> myList(int id)
    {
        DAO model1 = new DAO();
        List<Tovar> names = model1.listAllPerson(id);
        return names;
    }
    @Override
    public Tovar getTovar(int id) {
        DAO model1 = new DAO();
        return model1.showPersonInfo(id);
    }
    @Override
        public String getMessage() {
        return "This message was generated by simple ejb";
    }
    @Override
    public List<Tovar> getList() {
        AddBookBean a=new AddBookBean();
        return a.getList();
    }
    @Override
    public void sendEmail(String a,List<Tovar> as)
    {
        String to = a;         // sender email
        String from = "qwerty12345678901234567890123@yandex.ru";       // receiver email
        String host = "smtp.yandex.ru";            // mail server host

        Properties properties = System.getProperties();
        properties.setProperty("mail.smtp.host", "smtp.yandex.ru");
        properties.setProperty("mail.smtp.port", "465");
        properties.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        properties.setProperty("mail.smtp.socketFactory.port", "465");
        properties.setProperty("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.debug", "true");
        properties.put("mail.smtp.socketFactory.fallback", "false");
        Session session = Session.getDefaultInstance(properties,
                new javax.mail.Authenticator() {
                    @Override
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication("qwerty12345678901234567890123", "12581258");
                    }
                });



        try {
            MimeMessage message = new MimeMessage(session); // email message

            message.setFrom(new InternetAddress(from)); // setting header fields

            message.setRecipient(Message.RecipientType.TO, new InternetAddress(to));

            //message.setSubject("Test Mail from Java Program"); // subject line
            message.setSubject("Ваш заказ");
            // actual mail body
            String s=new String();
            s="Ваш заказ успешно оформлен"+"\n";
            for (Tovar b:as){
                s+=b.toString()+"\n";
            }
            message.setText(s);
            //Transport transport = session.getTransport("smtp");
            //transport.connect(host, 465, "qwerty12345678901234567890123", "12581258");
            //Transport.send(message, message.getAllRecipients());
            //transport.close();
            // Send message
            Transport.send(message);
            System.out.println("Email Sent successfully....");
        } catch (MessagingException mex){ mex.printStackTrace(); }

    }
    }
